# Python week 1

What is Programming ?

Programming is the process of giving instructions to a computer to perform a specific task or solve a problem. It involves writing a series of commands or code using a programming language that the computer can understand and execute.

Think of programming as a conversation between you and the computer. You provide a set of step-by-step instructions, and the computer follows those instructions to accomplish a particular goal.

Just like we use natural languages like English to communicate with each other, programming languages are designed to communicate with computers. However, programming languages have a more precise and structured syntax to ensure the computer can understand and execute the instructions correctly.

To write a program, you break down a problem into smaller, manageable steps, and then express those steps in the programming language of your choice. These steps might involve calculations, decision-making, repetition, and interaction with the computer's hardware or other software.

Once you've written the program, you can run it, and the computer will execute the instructions, producing the desired output or performing the intended task. Programming allows you to automate tasks, create software applications, build websites, analyze data, and much more.

Overall, programming is the art of writing instructions in a programming language to make computers do what you want them to do. It empowers you to solve problems and build a wide range of digital solutions.

What is automation?

In the context of programming, automation typically involves writing scripts or programs that can perform tasks that would otherwise require manual effort. This can include tasks such as data processing, file management, report generation, system administration, testing, and more.

Automation can be applied to various domains, including software development, data analysis, system administration, network management, and even everyday tasks like scheduling, email management, or data entry.

By automating repetitive tasks, programmers and other professionals can focus on more complex or creative aspects of their work, leading to increased productivity and improved results.

Overall, automation is a powerful concept in programming that enables the execution of tasks or processes automatically, freeing up human resources for more valuable work and improving overall productivity.

Python is a popular programming language. It was created by Guido van Rossum, and released in 1991.

It is used for:

- web development (server-side),
- software development,
- mathematics,
- system scripting.

What can Python do?

- Python can be used on a server to create web applications.
- Python can be used alongside software to create workflows.
- Python can connect to database systems. It can also read and modify files.
- Python can be used to handle big data and perform complex mathematics.
- Python can be used for rapid prototyping, or for production-ready software development.

Why Python?

- Python works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc).
- Python has a simple syntax similar to the English language.
- Python has syntax that allows developers to write programs with fewer lines than some other programming languages.
- Python runs on an interpreter system, meaning that code can be executed as soon as it is written. This means that prototyping can be very quick.
- Python can be treated in a procedural way, an object-oriented way or a functional way.

You can install python on your machine using the below link:
    
https://www.python.org/downloads/release/python-3114/

Also, you can download anaconda on your machine with below link:

https://www.anaconda.com/

Python is widely used in the IT field, including IT support, system administration, web development, machine learning, data analytics, and more. Python can be used to calculate statistics, run your e-commerce site, process images, interact with web services, and do a whole host of other tasks. Python instructions resemble the English language, which is what makes it easier to learn and understand when compared to other programming languages.

Python is:

- a general purpose scripting language;

- a popular language used to code a variety of applications;

- a frequently used tool for automation;

- a cross-platform compatible language;

- a beginner-friendly language.

Now that you've got an idea of what Python code looks like, let's check out one of the most basic examples and dive deeper into what's going on.

In [ ]:
print("Hello World!")

Print is a Python function that writes what we tell it to on the screen. Like the statement hello world for example, the print function is part of the basic Python language, whenever we use keywords or functions that are part of the language, we're using the programming language's syntax to tell the computer what to do.

So what are functions and keywords? 

Functions are pieces of code that perform a unit of work. We'll talk a lot more about functions later on, and you'll even learn how to write your own. Keywords are reserved words that are used to construct instructions. These words are the core part of the language and can only be used in specific ways. Some examples include if, while, and for. We'll explain all of those and a bunch more later in the course.

Wrapping text in quotation marks indicates that the text is considered a string, which means it's text that will be manipulated by our script. In programming, any text that isn't inside quotation marks is considered part of the code.

# Arithmetic operators

Python can calculate numbers using common mathematical operators, along with some special operators, too:  

- x + y            Addition + operator returns the sum of x plus y
- x - y             Subtraction - operator returns the difference of x minus y
- x * y            Multiplication * operator returns the product of x times y
- x / y             Division / operator returns the quotient of x divided by y
- x**e            Exponent ** operator returns the result of raising x to the power of e 
- x**2            Square expression returns x squared
- x**3            Cube expression returns x cubed
- x**(1/2)    Square root (½) or (0.5) fractional exponent operator returns the square root of x
- x // y           Floor division operator returns the integer part of the integer division of x by y
- x % y          Modulo operator returns the remainder part of the integer division of x by y

In [36]:
print(1+4)

5


In [37]:
print(100 * 25)

2500


In [38]:
print(-1/0.25)

-4.0


In [39]:
print(10 % 2)

0


# Python Data Types

In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

Python has the following data types built-in by default, in these categories:

- Text Type:	str
- Numeric Types:	int, float
- Sequence Types:	list, tuple, range
- Mapping Type:	dict
- Boolean Type:	bool
- Binary Types:	bytes, bytearray, memoryview

In [1]:
print(7+3)

10


In [2]:
len("Hello")

5

In [3]:
print("Hello" + "World")

HelloWorld


In [4]:
print(7.5 + "Hello")

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In Python, text in between quotes -- either single or double quotes -- is a string data type. An integer is a whole number, without a fraction, while a float is a real number that can contain a fractional part. For example, 1, 7, 342 are all integers, while 5.3, 3.14159 and 6.0 are all floats. When attempting to mix incompatible data types, you may encounter a TypeError. You can always check the data type of something using the type() function.

In [5]:
type("Hello")

str

In [6]:
type(7)

int

# Variables

Variables are names that we give to certain values in our programs. Those values can be of any data type; numbers, strings or even the results of operations.

Think of variables as containers for data. When you create a variable in your code, your computer reserves a chunk of its own memory to store that value. This lets the computer access the variable later to read or modify the value.

In [13]:
lenght = 50
width = 70
area = lenght * width
print(area)

3500


In [9]:
base = 12
height = 10
area = base + height
print(area)

22


Variables are important in programming because they let you perform operations on data that may change. For example, if we extended our rectangle script to accept any input as the value of the length and width variables, we could calculate the area of a rectangle of any size 

# Expressions, Numbers, and Type Conversions


In [14]:
print(7 + 4.5)

11.5


Behind the scenes the computer is busy automatically converting our integer seven into a float seven. This lets Python then add together the values to return a result that is also a float. We call this process implicit conversion. The interpreter automatically converts one data type into another. Python operations aren't just restricted to numbers.

In [22]:
base = 6
height = 3
area = base * height
print("The area of the triangle is = " + str(area))

The area of the triangle is = 18


In [26]:
a = 10

In [27]:
type(a)

int

In [28]:
float(a)

10.0

Implicit conversion is where the interpreter helps us out and automatically converts one data type into another, without having to explicitly tell it to do so.

By contrast, explicit conversion is where we manually convert from one data type to another by calling the relevant function for the data type we want to convert to.

# Expressions and Variables (overview)

- expression - a combination of numbers, symbols, or other values that produce a result when evaluated

- data types - classes of data (e.g., string, int, float, Boolean, etc.), which include the properties and behaviors of instances of the data type (variables)

- variable - an instance of a data type class, represented by a unique name within the code, that stores changeable values of the specific data type

- implicit conversion - when the Python interpreter automatically converts one data type to another

- explicit conversion - when code is written to manually convert one data type to another using a data type conversion function:

- str() - converts a value (often numeric) to a string data type

- int() - converts a value (usually a float) to an integer data type

- float() - converts a value (usually an integer) to a float data type

In [29]:
# The following lines assign the variable to the left of the = 
# assignment operator with the values and arithmetic expressions 
# on the right side of the = assignment operator.
hotel_room = 100
tax = hotel_room * 0.08
total = hotel_room + tax
room_guests = 4
share_per_person = total / room_guests


# This line outputs the result of the final calculation stored
# in the variable "share_per_person"
print("Each person needs to pay = " + str(share_per_person))

Each person needs to pay = 27.0


In [34]:
# The following 5 lines assign strings to a list of variables.
salutation = "Dr."
first_name = "Prisha"
middle_name = "Jai"
last_name = "Agarwal"
suffix = "(Ph.D.)"

a = salutation + " " + first_name + " " + middle_name + " " + last_name + " " + suffix
# The comma as a string ", " adds the conventional use of a comma plus a
# space to separate the last name from the suffix.
print(a)
# Alternatively, you could use commas in place of the + connector:
print(salutation, first_name, middle_name, last_name, suffix)
# However, you will find that this produces a space before a comma within a string.

Dr. Prisha Jai Agarwal (Ph.D.)
Dr. Prisha Jai Agarwal (Ph.D.)


In [35]:
print("5 * 3 = " + str(5*3))
# Resolution: 
# print("5 * 3 = " + str(5*3))
#
# To avoid a type error between the string and the integer within the
# print() function, you can make an explicit data type conversion by
# using the str() function to convert the integer to a string.

5 * 3 = 15


# Quiz

the code is supposed to display "2+2=4"

In [110]:
print("2 + 2 = " + str(2+2))

2 + 2 = 4


In this scenario, two friends are eating dinner at a restaurant. The bill comes in the amount of 47.28 dollars. The friends decide to split the bill evenly between them, after adding 15% tip for the service. Calculate the tip, the total amount to pay, and each friend's share, then output a message saying "Each person needs to pay: " followed by the resulting number.

In [111]:
bill = 47.28  # Assign "bill" variable with bill amount
tip_rate = 0.15  # Tip rate as a decimal (15% = 0.15)
tip = bill * tip_rate  # Multiply "bill" by tip rate to calculate the tip
total = bill + tip  # Sum "bill" and "tip" to calculate the total amount to pay
num_friends = 2  # Number of friends dining
share = total / num_friends  # Divide "total" by number of friends to calculate each friend's share

print("Each person needs to pay: $" + str(share))  # Output the message with the calculated share, converted to string

Each person needs to pay: $27.186


This code is supposed to take two numbers, divide one by another so that the result is equal to 1, and display the result on the screen. Unfortunately, there is an error in the code. Find the error and fix it, so that the output is correct.

In [112]:
numerator = 10.0
denominator = 10.0
result = numerator / denominator
print(result)

1.0


Combine the variables to display the sentence "How do you like Python so far?"

In [114]:
word1 = "How"
word2 = "do"
word3 = "you"
word4 = "like"
word5 = "Python"
word6 = "so"
word7 = "far?"

print(word1, word2, word3, word4, word5, word6, word7)
print(word1 + " " + word2 + " " + word3 + " " + word4 + " " + word5 + " " + word6 + " " + word7)

How do you like Python so far?
How do you like Python so far?


What do you call a combination of numbers, symbols, or other values that produce a result when evaluated?

Expression

# Functions

Python Functions is a block of statements that return the specific task. The idea is to put some commonly or repeatedly done tasks together and make a function so that instead of writing the same code again and again for different inputs, we can do the function calls to reuse code contained in it over and over again.

Some Benefits of Using Functions

- Increase Code Readability 
- Increase Code Reusability

We start a function definition with the def keyword, followed by the name we want to give our function. After the name, we have the parameters, also called arguments, for the function enclosed in parentheses. A function can have no parameters, or it can have multiple parameters. Parameters allow us to call a function and pass it data, with the data being available inside the function as variables with the same name as the parameters. Lastly, we put a colon at the end of the line.

After the colon, the function body starts. 

In [40]:
def first_function():
    print("Welcome to Jifunz!")

In [41]:
first_function()

Welcome to Jifunz!


In [69]:
def multiply(number1, number2):
    print(number1 * number2)

In [70]:
a = multiply(number1 = 10, number2 = 12)

120


In [71]:
b = multiply(number1 = 45, number2 = 32)

1440


In [72]:
print(a)

None


In [50]:
def greetings(name):
    print("Welcome to Jifunz! " + name)

In [51]:
greetings(name = "John")

Welcome to Jifunz! John


In [52]:
def third_function(name, departments, age):
    print("Welcome to our company, " + name)
    print("Your department is going to be = " + departments)
    print("Your age = " + str(age))

In [53]:
third_function("John", "IT", 27)

Welcome to our company, John
Your department is going to be = IT
Your age = 27


In [57]:
third_function(name = "John", age = 27, departments = "IT")

Welcome to our company, John
Your department is going to be = IT
Your age = 27


Sometimes we don't want a function to simply run and finish. We may want a function to manipulate data we passed it and then return the result to us. This is where the concept of return values comes in handy. We use the return keyword in a function, which tells the function to pass data back. When we call the function, we can store the returned value in a variable. Return values allow our functions to be more flexible and powerful, so they can be reused and called multiple times.

In [61]:
def area_triangle(base, height):
    return base * height / 2

In [62]:
area_a = area_triangle(10, 4)
area_b = area_triangle(7, 6)
sum_area = area_a + area_b
print(sum_area)

41.0


In [73]:
name = "Kay"
number = len(name) * 9
print("Welcome , " + name + " " + "Your lucky name is = " + str(number))

Welcome , Kay Your lucky name is = 27


In [78]:
def lucky_number(name):
    number = len(name) * 9
    return "Welcome , " + name + " " + "Your lucky name is = " + str(number)

In [81]:
a = lucky_number("John")

In [82]:
print(a)

Welcome , John Your lucky name is = 36


In [80]:
lucky_number("Suzia")

'Welcome , Suzia Your lucky name is = 45'

# Functions (Overview)

Terms

- return value - the value or variable returned as the end result of a function

- parameter (argument) -  a value passed into a function for use within the function

- refactoring code - a process to restructure code without changing functionality


Knowledge

- The purpose of the def() keyword is to define a new function. 

Best practices for writing code that is readable and reusable:

- Create a reusable function - Replace duplicate code with one reusable function to make the code easier to read and repurpose.

- Refactor code - Update code so that it is self-documenting and the intent of the code is clear.

- Add comments - Adding comments is part of creating self-documenting code. Using comments allows you to leave notes to yourself and/or other programmers to make the purpose of the code clear.

- Use a function that accepts multiple parameters

- Return a result value

In [123]:
# This function calculates the number of days in a variable number of 
# years, months, and days. These variables are provided by the user and
# are passed to the function through the function’s parameters.
def find_total_days(years, months, days):
# Assign a variable to hold the calculations for the number of days in
# a year (years*365) plus the number of days in a month (months*30) plus
# the number of days provided through the "days" parameter variable.
    my_day = (years * 365) + (months * 30) + days
# Use the "return" keyword to send the result of the "my_days"  
# calculation to the function call.
    return my_day
# Function call with user provided parameter values. 

In [124]:
print(find_total_days(2,5,23))

903


In [125]:
a = find_total_days(2,5,23)

In [126]:
print(a)

903


In [127]:
# This function converts fluid ounces to milliliters and returns the 
# result of the conversion.
def convert_volume(fluid_ounce):
# Calculate value of the "ml" variable using the parameter variable 
# "fluid_ounce". There are approximately 29.5 milliliters in 1 fluid
# ounce.
    ml = fluid_ounce * 29.5
# Return the result of the calculation.  
    return ml
# Call the conversion from within the print() function using 2 fluid 
# ounces. Convert the return value from a float to a string.  
print("The volume in millimeters is " + str(convert_volume(2)))
 
# Call the function again and double the 2 fluid ounces from within
# the print function.
print("The volume in millimeters is " + str(convert_volume(2) * 2))
# Alternative calculation:
# print("The volume in millimeters is " + str(convert_volume(4))

The volume in millimeters is 59.0
The volume in millimeters is 118.0


In [128]:
# 1) Complete the function to return the result of the conversion
def convert_distance(miles):
    # approximately 1.6 km in 1 mile
    km = miles * 1.6
    return km

# Do not indent any of the following lines of code as they are 
# meant to be located outside of the function above

my_trip_miles = 55

# 2) Convert my_trip_miles to kilometers by calling the function above
my_trip_km = convert_distance(my_trip_miles)

# 3) Fill in the blank to print the result of the my_trip_km conversion
print("The distance in kilometers is " + str(my_trip_km))

# 4) Calculate the round-trip in kilometers by doubling the result of
#    my_trip_km. Fill in the blank to print the result.
print("The round-trip in kilometers is " + str(my_trip_km * 2))

The distance in kilometers is 88.0
The round-trip in kilometers is 176.0


In [129]:
def print_seconds(hours, minutes, seconds):
    print(hours * (60*60) + minutes * 60 + seconds)


print_seconds(1,2,3)
#output will print to the screen

3723


In [132]:
def print_name(name):
    print("hello " + name)

In [133]:
print_name("John")

hello John


# Conditionals

Python can also compare values. This lets us check whether something is smaller than, equal to, or bigger than something else. This allows us to take the result of our expressions and use them to make decisions.

In [85]:
print(10 > 1)

True


True is a value that belongs to another data type called the Boolean. Booleans represent one of two possible states, either true or false. Every time you compare things in Python the result is a Boolean of the appropriate value. 

In [86]:
print("cat" == "dog")

False


In [88]:
print("cat" != "dog")

True


The comparison operators include: 

- "=="    (equality) 

- "!="    (not equal to) 

- ">"     (greater than)

- "<"     (less than)

- ">="    (greater than or equal to)

- "<="    (less than or equal to)

# Logical Operators

Logical operators are used to construct more complex expressions. You can make complex comparisons by joining comparison statements together using the logical operators: and, or, not. Complex comparisons return a Boolean (True or False) result. 

- and 

Both sides of the statement being evaluated must be True for the whole statement to be True. 

Example: (5 > 1 and 5 < 10) = True

- or 

If either side of the comparison is True, then the whole statement is True. 

Example: (color = "blue" or color = "green") = True

- not 

Inverts the Boolean result of the statement immediately following it. So, if a statement evaluates to True, and we put the not operator in front of it, it would become False. 

Example: (not "A" == "A") = False

# And

In Python, you can use the logical operator and to connect more than one comparison. This type of complex comparison is used to check if two comparison statements are both True or not. You might use the and operator when you need to execute a block of code, but only if two different conditions are true. For example, you might want to write a script  that automates sending you an emergency alert if a server stops responding and there is an unusual increase in employees opening trouble tickets.  

In [89]:
print((6*4 >= 18) and (9+9 <= 36/2))

True


In [90]:
print(10 < 9 and 11 > 10)

False


# Or

The or logical operator tests two conditions to determine if at least one side of the or logical operator is True. The result of the test can be used to trigger a block of code if at least one condition is present.


- True or True = True
- True or False = True
- False or True = True
- False or False = False

In [91]:
print(15/3 < 2+4 or 0 >= 6-7)

True


# Not

The not logical operator inverts the value of the comparison expression. This is a helpful tool when you want to execute a block of code as long as a certain condition is not present.

- If the conditional  expression is True, the not logical operator can be added to make the expression not True (False). 

- If the conditional  expression is False, the not logical operator can be added to make the expression not False (True).  

In [92]:
today = "Monday"
print(not today == "Tuesday")

True


# if Statements

There comes situations in real life when we need to make some decisions and based on these decisions, we decide what should we do next. Similar situations arise in programming also where we need to make some decisions and based on these decisions we will execute the next block of code. Decision-making statements in programming languages decide the direction(Control Flow) of the flow of program execution.

In [ ]:
if condition:

   statement1
   
statement2

In [135]:
i = 20

if i > 15:
    print("20 is greater than 15")


20 is greater than 15


In [96]:
def hint_username(username):
    if len(username) < 3:
        print("Invalid username, Must be at least 3 character long!")

In [97]:
hint_username("sa")

Invalid username, Must be at least 3 character long!


In [98]:
hint_username("sadegh")

# Else

what if we wanted the code to do something different if the evaluation is false? We can do this using the else statement. The else statement follows an if block, and is composed of the keyword else followed by a colon. The body of the else statement is indented to the right, and will be executed if the above if statement doesn’t execute.

In [99]:
def hint_username(username):
    if len(username) < 3:
        print("Invalid username, Must be at least 3 character long!")
    else:
        print("This is a valid username!")

In [100]:
hint_username("sadegh")

This is a valid username!


The is_positive function should return True if the number received is positive and False if it isn't.

In [136]:
def is_positive(number):
    if number > 0:
        return True
    else:
        return False

In [138]:
is_positive(-1)

False

write a function that can detect a number is even or not and call this function as is_even

In [139]:
def is_even(number):
    if number % 2 == 0:
        return True
    else:
        return False

In [141]:
is_even(12)

True

# Elif

Let's go back to our trusty username validation example. Now, what if your company also had a rule that usernames longer than 15 characters aren't allowed?

In [101]:
def hint_username(username):
    if len(username) < 3:
        print("Invalid Username, Must be at least 3 character long!")
    else:
        if len(username) > 15:
            print("Invalid Username, Must be at most 15 character long!")
        else:
            print("This is valid Username!")

Very similar to the if statements, an elif statement starts with the elif keyword, followed by a comparison to be evaluated. This is followed by a colon, and then the code block on the next line, indented to the right. An elif statement must follow an if statement, and will only be evaluated if the if statement was evaluated as false. You can include multiple elif statements to build complex branching in your code to do all kinds of powerful things!

In [104]:
def hint_username(username):
    if len(username) < 3:
        print("Invalid Username, must be at least 3 character long!")
    elif len(username) > 15:
        print("Invalid Username, Must be at most 15 character long!")
    else:
        print("Valid Username!")

In [105]:
hint_username('agdgafdsadjvajhdeqdddd')

Invalid Username, Must be at most 15 character long!


In [109]:
# Sets value of the "number" variable
number = 65
# The "number" variable will first be compared to 5. Since it is 
# False that "number" is not less than or equal to 5, the expression indented 
# under this line will be ignored. 
if number <= 5:
    print("The number is 5 or smaller")
 
# Next, the "number" variable will be compared to 33. Since it is 
# False that "number" is equal to 33, the expression indented under 
# this line will be ignored. 
elif number == 33:
    print("The number is 33.")
 
# Then, the "number" variable will be compared to 32 and 6. Since it 
# is True that 25 is less than 32 and greater than 6, the Python 
# interpreter will print "The number is less than 32 and/or greater
# than 6." Then, it will exit the if-elif-else statement and the remainder 
# of the if-elif-else statement will be ignored.
elif number < 32 and number >= 6:
    print("The number is less than 32 and greater than 6.")
else:
    print("The number is " + str(number))


 
# Expected output is:
# The number is less than 32 and greater than 6.

The number is 65


# Quiz

The function receives a name, then returns a greeting based on whether or not that name is "Taylor".

In [142]:
def greeting(name):
    if name == "Taylor":
        return "Welcome back Taylor!"
    else:
        return "Hello there, " + name

print(greeting("Taylor"))
print(greeting("John"))

Welcome back Taylor!
Hello there, John


What’s the output of this code if number equals 10?

In [143]:
number = 10
if number > 11:
    print(0)
elif number != 10:
    print(1)
elif number >= 20 or number < 12:
    print(2)
else:
    print(3)

2


If a filesystem has a block size of 4096 bytes, this means that a file comprised of only one byte will still use 4096 bytes of storage. A file made up of 4097 bytes will use 4096*2=8192 bytes of storage. Knowing this, can you fill in the gaps in the calculate_storage function below, which calculates the total number of bytes needed to store a file of a given size?

In [147]:
def calculate_storage(filesize):
    block_size = 4096
    # Use floor division to calculate how many blocks are fully occupied
    full_blocks = filesize // block_size
    # Use the modulo operator to check whether there's any remainder
    partial_block_remainder = filesize % block_size
    # Depending on whether there's a remainder or not, return
    # the total number of bytes required to allocate enough blocks
    # to store your data.
    if partial_block_remainder == 0:
        return full_blocks * block_size
    else:
        return (full_blocks + 1) * block_size

print(calculate_storage(1))    # Should be 4096
print(calculate_storage(4096)) # Should be 4096
print(calculate_storage(4097)) # Should be 8192
print(calculate_storage(6000)) # Should be 8192
print(calculate_storage(8192)) # Should be 8192

4096
4096
8192
8192
8192


block_size = 4096: This line sets the block_size to 4096 bytes, which is the size of each block in the filesystem.

full_blocks = filesize // block_size: Here, we use the floor division (//) to calculate how many complete blocks can be fully occupied by the given filesize. Floor division divides the filesize by the block_size and discards the remainder, giving us the number of complete blocks. For example, if the filesize is 8192 bytes, and the block_size is 4096 bytes, the result of filesize // block_size will be 2 because 8192 bytes can be divided evenly into two complete blocks of 4096 bytes each.

partial_block_remainder = filesize % block_size: The modulo operator (%) calculates the remaining bytes (partial_block_remainder) after filling the complete blocks. It returns the remainder of the division of filesize by block_size. For example, if the filesize is 8192 bytes, and the block_size is 4096 bytes, the result of filesize % block_size will be 0 because there are no remaining bytes after filling the complete blocks.

The if statement checks whether there's any remaining data that doesn't fit into a complete block (partial_block_remainder == 0). If there's no remainder, it means the filesize is already a multiple of the block size, and we can store the data in complete blocks without any additional space.

If there's no remainder (partial_block_remainder == 0), we return the total size as full_blocks * block_size, which is the number of complete blocks multiplied by the block size.

If there's a remainder, it means we need an additional block to store the remaining data. So, we return the total size as (full_blocks + 1) * block_size, which is the number of complete blocks plus one (to accommodate the remaining data) multiplied by the block size.


In [149]:
8192 // 4096

2

In [150]:
8192 % 4096

0

# Week 1 & 2 Recap

In [ ]:
# A function is created with the def() keyword. The parameter
# variable "time_as_string" is passed to the function through a 
# call to the function.
def task_reminder(time_as_string):

    # The following if-elif-else block assigns various strings to
    # the variable "task" depending on specific conditions. The
    # test conditions are set using the == equality comparison 
    # operator. In this case, the time passed through the 
    # "time_as_string" parameter variable is tested as the 
    # specific condition. So, if the time  is "11:30 a.m.", then 
    # "task" is assigned the value: "Run TPS report".
    if time_as_string == "8:00 a.m.":
        task = "Check overnight backup images"
    elif time_as_string == "11:30 a.m.":
        task = "Run TPS report"
    elif time_as_string == "5:30 p.m.":
        task = "Reboot servers"
    # The else statement is a catchall for all other values of 
    # the "time_as_string" parameter variable not listed in the
    # if-elif block of code.
    else:
        task = "Provide IT Support to employees"

    # This line returns the value of "task" to the function call.
    return task

# This line calls the function and passes a parameter  
# ("10:00 a.m.") to the function.
print(task_reminder("10:00 a.m."))
# Should print "Provide IT Support to employees"


In [ ]:
number1 = 10
number2 = 50
number1 * number2

In [152]:
# multiply two parameter in function
def multiply(a, b):
    return a * b

multiply(multiply(10,20), multiply(30,3))

18000

Write a function that can minus two numbers

In [153]:
def difference(a, b):
    return a - b

Write a function that can sum two numbers

In [154]:
def sum(a, b):
    return a + b

In [155]:
difference(sum(10,20), sum(87,21))

-78

Write a function that can get the remainder of two number

In [156]:
def get_remainder(a, b):
    if a == 0 or b == 0:
        remainder = 0
    else:
        remainder = a % b
    return remainder
print(get_remainder(10, 3))

1


write a function which compares two numbers and returns them as increasing order

In [158]:
# This function compares two numbers and returns them
# in increasing order.
def order_number(number1, number2):
    if number1 > number2:
        return number2, number1
    else:
        return number1, number2

# 1) Fill in the blanks so the print statement displays the result
#    of the function call
smaller, bigger = order_number(100, 99)
print(smaller, bigger)

99 100


Write a Python function called classify_number that takes an integer as input and returns a string indicating whether the number is positive, negative, or zero.

In [161]:
def classify_number(number):
    if number > 0:
        return "Positive"
    elif number < 0:
        return "Negative"
    else:
        return "Zero"

result = classify_number(-1)
print(result)  # Output: "Positive"

Negative


Write a Python function called get_grade that takes a numerical score as input and returns the corresponding letter grade based on the following grading scale:

- 90 or above: "A"
- 80 to 89: "B"
- 70 to 79: "C"
- 60 to 69: "D"
- Below 60: "F"

In [163]:
def get_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else:
        return "F"
    

result = get_grade(60)
print(result)  # Output: "D"

D


Write a Python function called check_divisibility that takes two integers, num and divisor, as input. The function should check if num is divisible by divisor without any remainder. If it is, the function should return the message "Divisible". Otherwise, it should return the message "Not divisible".

In [164]:
def check_divisibility(num, divisor):
    if num % divisor == 0:
        return "Divisible"
    else:
        return "Not divisible"
    
result = check_divisibility(12, 4)
print(result)  # Output: "Divisible"

Divisible


Write a Python function called is_even_length that takes a string as input and returns True if the length of the string is even, and False otherwise.

In [165]:
def is_even_length(input_string):
    if len(input_string) % 2 == 0:
        return True
    else:
        return False
    
result = is_even_length("Hell")
print(result)  # Output: True


True


Write a Python function called is_triangle that takes three positive integers, side1, side2, and side3, as input. The function should check if the three integers can form the sides of a triangle. If they can, the function should return True. Otherwise, it should return False. According to the triangle inequality theorem, for a triangle to be valid, the sum of the lengths of any two sides must be greater than the length of the third side.

In [171]:
def is_triangle(side1, side2, side3):
    if side1 + side2 > side3 or side1 + side3 > side2 or side3 + side2 > side1:
        return True
    else:
        return False

result = is_triangle(3, 4, 5)
print(result)  # Output: True


True


Write a Python function called is_string_empty that takes a string as input and determines if it is empty. If the string is empty, the function should return True. Otherwise, it should return False.

In [172]:
def is_string_empty(input_string):
    if len(input_string) > 0:
        return False
    else:
        return True

result = is_string_empty("")
print(result)  # Output: True

True


Write a function called greet_person that takes a name and a time of day (either "morning," "afternoon," or "evening") as its arguments and returns a personalized greeting message based on the provided inputs.

In [173]:
def greet_person(name, time_of_day):
    if time_of_day == "morning":
        greeting = "Good morning"
    elif time_of_day == "afternoon":
        greeting = "Good afternoon"
    elif time_of_day == "evening":
        greeting = "Good evening"
    else:
        greeting = "Hello"
    
    return f"{greeting}, {name}!"

# Test the function
print(greet_person("Alice", "morning"))
# Should print "Good morning, Alice!"

Good morning, Alice!


Write a function called convert_temperature that takes a temperature value and a unit ("C" for Celsius or "F" for Fahrenheit) as its arguments and returns the converted temperature value in the other unit. Implement the conversion formulas:

- Celsius to Fahrenheit: (C × 9/5) + 32
- Fahrenheit to Celsius: (F - 32) × 5/9

In [174]:
def convert_temperature(value, unit):
    if unit == "C":
        converted_value = (value * 9/5) + 32
        new_unit = "Fahrenheit"
    elif unit == "F":
        converted_value = (value - 32) * 5/9
        new_unit = "Celsius"
    else:
        return "Invalid unit"

    return f"{value} {unit} is {converted_value:.2f} {new_unit}"

# Test the function
print(convert_temperature(30, "C"))
# Should print "30 C is 86.00 Fahrenheit"


30 C is 86.00 Fahrenheit


Write a function called calculate_tip that takes a bill amount and a tip percentage as its arguments and returns the total amount, including the tip.

In [175]:
def calculate_tip(bill_amount, tip_percentage):
    if tip_percentage < 0 or tip_percentage > 100:
        return "Invalid tip percentage"
    
    tip_amount = (tip_percentage / 100) * bill_amount
    total_amount = bill_amount + tip_amount
    
    return f"Total amount: ${total_amount:.2f}"

# Test the function
print(calculate_tip(50, 15))
# Should print "Total amount: $57.50"

Total amount: $57.50


# QUIZ

Complete the code to output the statement, “192.168.1.10 is the IP address of Printer Server 1”. Remember that precise syntax must be used to receive credit.

In [176]:
IP_address = "192.168.1.10"
host_name = "Printer Server 1"
print(IP_address + "is the IP address of " + host_name)
# Should print "192.168.1.10 is the IP address of Printer Server 1"

192.168.1.10is the IP address of Printer Server 1


What is the value of this Python expression: "blue" == "Blue"?

In [ ]:
"blue" == "Blue"

What is the elif keyword used for?

To handle more than two comparison cases

Consider the following scenario about using if-elif-else statements:

The fall weather is unpredictable. If the temperature is below 32 degrees Fahrenheit, a heavy coat should be worn. If it is above 32 degrees but not above 50 degrees, then a jacket should be sufficient. If it is above 50 but not above 65 degrees, a sweatshirt is appropriate, and above 65 degrees a t-shirt can be worn. Fill in the blanks in the function below so it returns the proper clothing type for the temperature.

In [177]:
def clothing_type(temp):
    if temp > 65:
        clothing = "T-Shirt"
    elif temp > 50:
        clothing = "Sweatshirt"
    elif temp > 32:
        clothing = "Jacket"
    else:
        clothing = "Heavy Coat"
    return clothing


print(clothing_type(72)) # Should print T-Shirt
print(clothing_type(55)) # Should print Sweatshirt
print(clothing_type(65)) # Should print Sweatshirt
print(clothing_type(50)) # Should print Jacket
print(clothing_type(45)) # Should print Jacket
print(clothing_type(32)) # Should print Heavy Coat
print(clothing_type(0)) # Should print Heavy Coat

T-Shirt
Sweatshirt
Sweatshirt
Jacket
Jacket
Heavy Coat
Heavy Coat


What's the value of the comparison in this if statement? Hint: The answer is not what the code will print.

In [ ]:
n = 4
if n*6 > n**2 or n%2 == 0:
    print("Check")

Fill in the blanks to complete the function. The character translator function receives a single lowercase letter, then prints the numeric location of the letter in the English alphabet. For example, “a” would return 1 and “b” would return 2. Currently, this function only supports the letters “a”, “b”, “c”, and “d” It returns "unknown" for all other letters or if the letter is uppercase.

In [178]:
def letter_translator(letter):
    if letter == "a":
        letter_position = 1
    elif letter == "b":
        letter_position = 2
    elif letter == "c":
        letter_position = 3
    elif letter == "d":
        letter_position = 4
    else:
        letter_position = "unknown"
    return letter_position


print(letter_translator("a")) # Should print 1
print(letter_translator("b")) # Should print 2
print(letter_translator("c")) # Should print 3
print(letter_translator("d")) # Should print 4
print(letter_translator("e")) # Should print unknown
print(letter_translator("A")) # Should print unknown
print(letter_translator("")) # Should print unknown

1
2
3
4
unknown
unknown
unknown


Can you calculate the output of this code?

In [ ]:
def difference(x, y):
    z = x - y
    return z


print(difference(5, 3))

What's the value of this Python expression?

In [ ]:
((10 >= 5*2) and (10 <= 5*2))

Fill in the blanks to complete the function. The “make_positive” function takes in a number and converts that number to its positive equivalent.  Complete the function to accomplish the following tasks:

- use an if statement to test if the number is negative;
- use a calculation inside the if statement to change the negative number to be positive;
- use a calculation in the else statement to return any positive “number” unchanged.

In [179]:
def make_positive(number):
    if number < 0:
        result = number * -1
    else:
        result = number
    return result

print(make_positive(-4))   # Should print 4
print(make_positive(0))    # Should print 0
print(make_positive(-.25)) # Should print 0.25
print(make_positive(5))    # Should print 5

4
0
0.25
5
